services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python:
    container_name: python
    build: .
    depends_on: 
      - postgres
    env_file:
      - .env
    stdin_open: true
    tty: true
    
volumes:
  postgres_data: